### ISSUE TITLE
Illegal Message Shown With Dev Branch

### ISSUE THREAD

**Issue by whitefirdesign** [Zen4All/Zen-Cart_SuperOrders#6]
In the dev branch, the file /1_Base_Files/YOUR_ADMIN/includes/init_includes/init_so_config.php is causing the message "Illegal" to be shown instead of admin pages due to "access" being misplaced in the following lines of code:

```
 if (!defined('IS_accessADMIN_FLAG')) {
     die('Illegal ');
```

**Comment by Zen4All** [comment]
Thanks, yes found that one myself too. will post the fix shortly
